apiVersion: sql.databases/v1beta2
kind: GaleraBackup
metadata:
  name: galera-backup
  namespace: galera
spec:
  galeraName: gal
#  galeraNamespace: galera
  backupMethodType: mariabackup
  mariabackup:
    credentialsBackup:
      name: galera-secret
  storageProviderType: S3
  s3:
#    region:
    endpoint: $YOURENDPOINT
    bucket: save
#    forcePathStyle:
    credentialsSecret:
      name: s3-secret