apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: galera-operator
  namespace: galera
rules:
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
