apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: galera-cluster
  namespace: galera
  labels:
    team: galera
spec:
  selector:
    matchLabels:
      galera-cluster: galera
      owner: sebs42
      stage: dev
  namespaceSelector:
    matchNames:
      - galera
  endpoints:
    - port: metrics
      interval: 10s
      scheme: http
